### ISSUE TITLE
Add support for Workload Identity authentication

### ISSUE THREAD

**Issue by baburciu** [upbound/function-azresourcegraph#78]
### What problem are you facing?

I don't know if it makes sense implementation-wise, since this is a function, but maybe you could consider adding Workload Identity support. This authentication method is already supported in [`provider-upjet-azure`](https://github.com/crossplane-contrib/provider-upjet-azure), where more options are available for the [credentials source](https://github.com/crossplane-contrib/provider-upjet-azure/blob/v1.13.0/package/crds/azure.upbound.io_providerconfigs.yaml#L105-L145).

Although documentation for Workload Identity usage with the provider is limited, the following references demonstrate a common approach for configuring the Crossplane provider with Managed Identity:
- https://github.com/crossplane-contrib/provider-azure/issues/329#issuecomment-1904583342
- https://github.com/crossplane-contrib/provider-azure/issues/329#issuecomment-2595820451

We also use [this](https://github.com/crossplane-contrib/provider-azure/issues/329#issuecomment-1904583342) and it works.

Supporting Workload Identity for the `function-azresourcegraph` would enable secure, Secret-less authentication, eliminating the need for static credentials while aligning with other Azure providers in Crossplane.

### How could this Function help solve your problem?

We could install the function with:
```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  annotations:
  name: function-azresourcegraph-config
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        metadata:
          labels:
            azure.workload.identity/use: 'true'   # <==
        spec:
          securityContext:
            fsGroup: 2000
  serviceAccountTemplate:
    metadata:
      annotations:
        azure.workload.identity/client-id: 'foo'  # <==
        azure.workload.identity/tenant-id: 'bar'  # <==
      name: function-azresourcegraph-sa
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-azresourcegraph
spec:
  package: xpkg.upbound.io/upbound/function-azresourcegraph:v0.9.0
  packagePullPolicy: Always
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: function-azresourcegraph-config
```
and reference it in a Composition pipeline step with a `credentials` block like
```yaml
  pipeline:
    - step: query-azresourcegraph
      functionRef:
        name: function-azresourcegraph
      input:
        apiVersion: azresourcegraph.fn.crossplane.io/v1alpha1
        kind: Input
        query: |
               Resources
               | where type =~ 'microsoft.sql/servers/databases'
               | order by name desc
        target: "context.azResourceGraphQueryResult"
      credentials:
        - source: OIDCTokenFile
          oidcTokenFilePath: /var/run/secrets/azure/tokens/azure-identity-token
          clientID: 'foo'
          tenantID: 'bar'
          subscriptionID: 'toto'
```

Trying this today returns:
```
[spec.pipeline[0].credentials[0].source: Unsupported value: "OIDCTokenFile": supported values: "None", "Secret", spec.pipeline[0].credentials[0].name: Required value, <nil>: Invalid value: "null"
```
